[package]
name = "royal_game_of_ur"
version = "0.1.0"
authors = ["rhapsodos <ichumonji@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod = "0.61.1"
rand = "~0.3"
